replicaCount: 1

image:
  repository: vladimirkhil/spard
  tag: "1.0.9"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  clientSecret: ''
  hosts: []
  tls: []

resources: {}

options:
  logLevel: Warning
  otel:
    uri: 'http://localhost:4317'
    metric:
      exportInterval: 60000
