replicaCount: 1

image:
  repository: vladimirkhil/spard
  tag: "1.0.8"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources: {}
